app:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/LMS_PROFILE_SERVICE
    username: lms
    password: lms123
    configuration:
      max-pool-size: 50
server:
  port: 8003
  servlet:
    context-path: /lms-profile-service
spring:
  application:
    name: lms-profile-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

